
name: build-3

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    types: [ labeled ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  no-build:
    runs-on: ubuntu-latest
    steps:
      - run: if [ "${{ github.event.label.name  }}" == 'build3' ]; then exit 0; else exit 1; end

  # This workflow contains a single job called "build"
  build-4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [no-build]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
